apiVersion: v1
kind: Service
metadata:
  name: pochaakshybridapi
  namespace: default
  labels:
    run: pochaakshybridapi
spec:
  selector:
    run: pochaakshybridapi
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
